Fix utf-8 breaking error
I got an error that might be due to an URL containing utf-8 character (in my case, a `é`):

```
Traceback (most recent call last):
  File "/home/zeecka/.BurpSuite/bapps/f991b67d4ef94f3c8692c3edca06583e/site_map_extractor.py", line 390, in exportCodes
    self.urlDecode = self._helpers.urlDecode(str(self.url))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 56-58: ordinal not in range(128)
```